version: "3"

services:
  backend:
    build:
      context: ./ismac_backend
    command: "gunicorn ismac_backend.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - backend_media:/app/media

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile

    ports:
      - "80:8080"
      - "81:8181"
      - "443:443"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

    depends_on:
      - backend
      - db

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw

  db:
    image: postgres:latest
    restart: unless-stopped

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ISMAC_DB
      - POSTGRES_USER=UUSR
      - POSTGRES_PASSWORD=aoishdqiwuf13213edn1i21x012u09x12ue28e12837eds128
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - pg_data:/var/lib/postgresql/data/:rw

volumes:
  pg_data:
  backend_media:
