# Generated by Django 5.0.4 on 2024-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_studentdata_portfolio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
