# Generated by Django 5.0.4 on 2024-07-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_studentdata_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
