# Generated by Django 5.0.4 on 2024-07-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_studentdata_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
