# Generated by Django 5.0.4 on 2024-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_studentdata_cin_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='is_foreign_bac',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
