# Generated by Django 5.0.4 on 2024-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rename_bac_year_studentdata_diplome_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='licence_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
