# Generated by Django 5.0.4 on 2024-11-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_studentdata_licence_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='bac_note',
            new_name='diplome_note',
        ),
    ]
